<#include "components/barcode.ftl">
<#include "components/qrcode.ftl">
<#include "components/title_setting.ftl">
<#include "components/bar_setting.ftl">
<#include "components/line_setting.ftl">
<#include "components/pie_setting.ftl">
<#include "components/margin_setting.ftl">
<#include "components/funnel_setting.ftl">
<#include "components/pictorial_setting.ftl">
<#include "components/scatter_setting.ftl">
<#include "components/map_setting.ftl">
<#include "components/radar_setting.ftl">
<#include "components/gauge_setting.ftl">
<#include "components/xAxis_setting.ftl">
<#include "components/yAxis_setting.ftl">
<#include "components/series_setting.ftl">
<#include "components/tooltip_setting.ftl">
<#include "components/grid_setting.ftl">
<#include "components/legend_setting.ftl">
<#include "components/background_setting.ftl">
<#include "components/match_setting.ftl">
<#include "components/data_source_setting.ftl">
<#include "components/central_point_setting.ftl">
<#include "components/function_interpretation.ftl">
<#include "components/data_dictionary.ftl">